### ISSUE TITLE
Add Support for Compact mode (js-Controller 2.0 Feature)

### ISSUE THREAD

**Issue by ldittmar81** [dna909/ioBroker.homeconnect#11]
The upcoming version 2.0.0 of js-controller will support a new mode for low memory devices. For this, a few minor adjustments to the adapter must be made. Please follow these instructions: https://forum.iobroker.net/viewtopic.php?f=24&t=20387#p213466

**Comment by dna909** [comment]
Wenn jemand Zeit und Lust hat, kann er das gerne umsetzen :-)

**Comment by firelook** [comment]
it seems it is broken : doesn't work anymore

`

homeconnect.0 | 2019-04-06 20:15:57.882 | warn | Too many requests. Adapter sends too many requests per minute.
-- | -- | -- | --
homeconnect.0 | 2019-04-06 20:15:57.882 | error | Error (SIEMENS-SN778D16TE-68A40E23A59D)
homeconnect.0 | 2019-04-06 20:15:57.882 | error | 429
homeconnect.0 | 2019-04-06 20:15:57.567 | info | Accestoken renewed...
homeconnect.0 | 2019-04-06 19:15:57.613 | warn | Too many requests. Adapter sends too many requests per minute.
homeconnect.0 | 2019-04-06 19:15:57.613 | error | Error (SIEMENS-SN778D16TE-68A40E23A59D)
homeconnect.0 | 2019-04-06 19:15:57.613 | error | 429
homeconnect.0 | 2019-04-06 19:15:57.351 | info | Accestoken renewed...
homeconnect.0 | 2019-04-06 18:15:57.571 | warn | Too many requests. Adapter sends too many requests per minute.
homeconnect.0 | 2019-04-06 18:15:57.571 | error | Error (SIEMENS-SN778D16TE-68A40E23A59D)
homeconnect.0 | 2019-04-06 18:15:57.571 | error | 429
homeconnect.0 | 2019-04-06 18:15:57.292 | info | Accestoken renewed...
homeconnect.0 | 2019-04-06 17:15:57.527 | warn | Too many requests. Adapter sends too many requests per minute.
homeconnect.0 | 2019-04-06 17:15:57.527 | error | Error (SIEMENS-SN778D16TE-68A40E23A59D)
homeconnect.0 | 2019-04-06 17:15:57.527 | error | 429
homeconnect.0 | 2019-04-06 17:15:57.227 | info | Accestoken renewed...
homeconnect.0 | 2019-04-06 16:15:57.391 | warn | Too many requests. Adapter sends too many requests per minute.
homeconnect.0 | 2019-04-06 16:15:57.391 | error | Error (SIEMENS-SN778D16TE-68A40E23A59D)
homeconnect.0 | 2019-04-06 16:15:57.390 | error | 429
homeconnect.0 | 2019-04-06 16:15:57.111 | info | Accestoken renewed...
homeconnect.0 | 2019-04-06 15:15:57.597 | warn | Too many requests. Adapter sends too many requests per minute.
homeconnect.0 | 2019-04-06 15:15:57.597 | error | Error (SIEMENS-SN778D16TE-68A40E23A59D)
homeconnect.0 | 2019-04-06 15:15:57.597 | error | 429
homeconnect.0 | 2019-04-06 15:15:56.901 | info | Accestoken renewed...
homeconnect.0 | 2019-04-06 14:15:57.513 | warn | Too many requests. Adapter sends too many requests per minute.
homeconnect.0 | 2019-04-06 14:15:57.513 | error | Error (SIEMENS-SN778D16TE-68A40E23A59D)
homeconnect.0 | 2019-04-06 14:15:57.512 | error | 429
homeconnect.0 | 2019-04-06 14:15:56.858 | info | Accestoken renewed...
homeconnect.0 | 2019-04-06 13:15:57.117 | warn | Too many requests. Adapter sends too many requests per minute.
homeconnect.0 | 2019-04-06 13:15:57.117 | error | Error (SIEMENS-SN778D16TE-68A40E23A59D)
homeconnect.0 | 2019-04-06 13:15:57.117 | error | 429
homeconnect.0 | 2019-04-06 13:15:56.841 | info | Accestoken renewed...
homeconnect.0 | 2019-04-06 12:15:57.134 | warn | Too many requests. Adapter sends too many requests per minute.
homeconnect.0 | 2019-04-06 12:15:57.133 | error | Error (SIEMENS-SN778D16TE-68A40E23A59D)
homeconnect.0 | 2019-04-06 12:15:57.133 | error | 429
homeconnect.0 | 2019-04-06 12:15:56.846 | info | Accestoken renewed...
homeconnect.0 | 2019-04-06 11:15:56.677 | info | Accestoken renewed...
homeconnect.0 | 2019-04-06 10:15:56.277 | info | Accestoken renewed...
homeconnect.0 | 2019-04-06 09:15:56.167 | info | Accestoken renewed...
homeconnect.0 | 2019-04-06 08:15:56.105 | info | Accestoken renewed...
homeconnect.0 | 2019-04-06 07:15:55.948 | info | Accestoken renewed...
homeconnect.0 | 2019-04-06 06:15:55.828 | info | Accestoken renewed...
homeconnect.0 | 2019-04-06 05:15:55.886 | info | Accestoken renewed...
homeconnect.0 | 2019-04-06 04:15:55.785 | info | Accestoken renewed...
homeconnect.0 | 2019-04-06 03:15:55.920 | info | Accestoken renewed...
homeconnect.0 | 2019-04-06 02:15:55.738 | info | Accestoken renewed...
host.Obelix | 2019-04-06 01:37:45.465 | info | Delete log file iobroker.2019-03-30.log
homeconnect.0 | 2019-04-06 01:16:05.307 | error | Irgendwas stimmt da wohl nicht!! Refresh-Token!! Fehlercode: 504
homeconnect.0 | 2019-04-06 00:16:05.302 | error | Error getting homeapplianceJSON with Token. Fehlercode: 504,Timeout on Home Connect subsystem. Please try it again.
homeconnect.0 | 2019-04-06 00:15:55.127 | info | starting. Version 0.0.7 in C:/iobroker/node_modules/iobroker.homeconnect, node: v6.11.3
host.Obelix | 2019-04-06 00:15:53.218 | info | instance system.adapter.homeconnect.0 started with pid 8296
host.Obelix | 2019-04-06 00:15:23.198 | info | Restart adapter system.adapter.homeconnect.0 because enabled
host.Obelix | 2019-04-06 00:15:23.198 | error | instance system.adapter.homeconnect.0 terminated with code 0 (OK)
Caught | 2019-04-06 00:15:23.198 | error | by controller[0]: at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
Caught | 2019-04-06 00:15:23.198 | error | by controller[0]: at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
Caught | 2019-04-06 00:15:23.198 | error | by controller[0]: at ClientRequest.emit (events.js:188:7)
Caught | 2019-04-06 00:15:23.198 | error | by controller[0]: at emitOne (events.js:96:13)
Caught | 2019-04-06 00:15:23.198 | error | by controller[0]: at ClientRequest.g (events.js:292:16)
Caught | 2019-04-06 00:15:23.198 | error | by controller[0]: at ClientRequest.<anonymous> (C:\iobroker\node_modules\iobroker.homeconnect\node_modules\eventsource\lib\eventsource.js:136:9)
Caught | 2019-04-06 00:15:23.198 | error | by controller[0]: at _emit (C:\iobroker\node_modules\iobroker.homeconnect\node_modules\eventsource\lib\eventsource.js:242:17)
Caught | 2019-04-06 00:15:23.198 | error | by controller[0]: at EventSource.emit (events.js:188:7)
Caught | 2019-04-06 00:15:23.198 | error | by controller[0]: at emitOne (events.js:96:13)
Caught | 2019-04-06 00:15:23.197 | error | by controller[0]: at EventSource.eventSource.onerror.err (C:\iobroker\node_modules\iobroker.homeconnect\main.js:274:27)
Caught | 2019-04-06 00:15:23.189 | error | by controller[0]: Error: 504
homeconnect.0 | 2019-04-06 00:15:23.096 | info | terminating
homeconnect.0 | 2019-04-06 00:15:23.092 | info | cleaned everything up...
homeconnect.0 | 2019-04-06 00:15:23.091 | error | at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
homeconnect.0 | 2019-04-06 00:15:23.091 | error | at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
homeconnect.0 | 2019-04-06 00:15:23.091 | error | at ClientRequest.emit (events.js:188:7)
homeconnect.0 | 2019-04-06 00:15:23.091 | error | at emitOne (events.js:96:13)
homeconnect.0 | 2019-04-06 00:15:23.091 | error | at ClientRequest.g (events.js:292:16)
homeconnect.0 | 2019-04-06 00:15:23.091 | error | at ClientRequest.<anonymous> (C:\iobroker\node_modules\iobroker.homeconnect\node_modules\eventsource\lib\eventsource.js:136:9)
homeconnect.0 | 2019-04-06 00:15:23.091 | error | at _emit (C:\iobroker\node_modules\iobroker.homeconnect\node_modules\eventsource\lib\eventsource.js:242:17)
homeconnect.0 | 2019-04-06 00:15:23.091 | error | at EventSource.emit (events.js:188:7)
homeconnect.0 | 2019-04-06 00:15:23.091 | error | at emitOne (events.js:96:13)
homeconnect.0 | 2019-04-06 00:15:23.091 | error | at EventSource.eventSource.onerror.err (C:\iobroker\node_modules\iobroker.homeconnect\main.js:274:27)
homeconnect.0 | 2019-04-06 00:15:23.091 | error | Error: 504
homeconnect.0 | 2019-04-06 00:15:23.091 | error | uncaught exception: 504
homeconnect.0 | 2019-04-06 00:15:23.067 | error | FEHLER
homeconnect.0 | 2019-04-06 00:15:23.067 | error | Error (SIEMENS-SN778D16TE-68A40E23A59D)
homeconnect.0 | 2019-04-06 00:15:23.066 | error | 504
homeconnect.0 | 2019-04-06 00:15:12.121 | error | undefined
homeconnect.0 | 2019-04-06 00:15:11.998 | error | undefined
homeconnect.0 | 2019-04-06 00:15:04.672 | warn | Too many requests. Adapter sends too many requests per minute.
homeconnect.0 | 2019-04-06 00:15:04.672 | error | Error (SIEMENS-SN778D16TE-68A40E23A59D)
homeconnect.0 | 2019-04-06 00:15:04.672 | error | 429

`
